/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author bridge-ai
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regisPicture = new javax.swing.JLabel();
        StudentIdTextField = new javax.swing.JTextField();
        stIdRegisLabel = new javax.swing.JLabel();
        passRegisLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        fullNameTextField = new javax.swing.JTextField();
        nameRegisLabel = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        regisTextLabel = new javax.swing.JLabel();
        registratioinLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regisPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/unnamed (1) 1.png"))); // NOI18N
        regisPicture.setToolTipText("");
        jPanel1.add(regisPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));
        jPanel1.add(StudentIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 320, 35));

        stIdRegisLabel.setForeground(new java.awt.Color(255, 255, 255));
        stIdRegisLabel.setText("รหัสนักศีกษา");
        jPanel1.add(stIdRegisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        passRegisLabel.setForeground(new java.awt.Color(255, 255, 255));
        passRegisLabel.setText("รหัสผ่าน");
        jPanel1.add(passRegisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));
        jPanel1.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 320, 35));
        jPanel1.add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 320, 35));

        nameRegisLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameRegisLabel.setText("ชื่อ-นามสกุล");
        jPanel1.add(nameRegisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("สร้างบัญชี");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, 40));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setText("ย้อนกลับ");
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, 40));

        regisTextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        regisTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        regisTextLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/ลงทะเบียน.png"))); // NOI18N
        jPanel1.add(regisTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        registratioinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Group 11.png"))); // NOI18N
        jPanel1.add(registratioinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    public JTextField getStudentIdTextField() {
        return StudentIdTextField;
    }

    public void setStudentIdTextField(JTextField StudentIdTextField) {
        this.StudentIdTextField = StudentIdTextField;
    }

    public JTextField getFullNameTextField() {
        return fullNameTextField;
    }

    public void setFullNameTextField(JTextField fullNameTextField) {
        this.fullNameTextField = fullNameTextField;
    }

    public JButton getSubmitBtn() {
        return submitBtn;
    }

    public void setSubmitBtn(JButton submitBtn) {
        this.submitBtn = submitBtn;
    }

    public JTextField getPasswordTextField() {
        return passwordTextField;
    }

    public void setPasswordTextField(JTextField passwordTextField) {
        this.passwordTextField = passwordTextField;
    }

    public JButton getBackBtn() {
        return backBtn;
    }

    public void setBackBtn(JButton backBtn) {
        this.backBtn = backBtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StudentIdTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameRegisLabel;
    private javax.swing.JLabel passRegisLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel regisPicture;
    private javax.swing.JLabel regisTextLabel;
    private javax.swing.JLabel registratioinLabel;
    private javax.swing.JLabel stIdRegisLabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
